### ISSUE TITLE
Question: how to deploy on HA/Supervisor?

### ISSUE THREAD

**Issue by alexciesielski** [troyanskiy/tsnode-homeassistant#1]
This library looks great, just found it and looking at the possibility to do my automations using this instead of NodeRed.

I'm wondering though if or rather how to deploy this to HA/Supervisor so I don't need to maintain a separate server to run this? Any idea or suggestions?

Again thanks for this lib, forking it and looking forward to opening PRs

**Comment by troyanskiy** [comment]
WOW!
I did not expect that someone will use it :) thanks!
For the moment I did not thought (I don't have time) how to make it easy to deploy to HA/Supervisor.
I'm deploying as docker container on my home ha server.

**Comment by alexciesielski** [comment]
Thanks for your reply. I figured it out and opened a PR to your seed project :)
